config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  get 'search' => 'searches#search'
  # For details onthe DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
    <% user.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
        <td><%= user.name %></th>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user.followings.count, user_followings_path(user)  %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user.followers.count, user_followers_path(user)  %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if current_user.followings?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
  <%= render 'relationships/follow', user: @users %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
  <%= render 'relationships/follow', user: @users %>