config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  get 'search' => 'searches#search'
  # For details onthe DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @search_model = params[:search_model]
    @word = params[:word]

    if @search_model == "user"
      @users = User.looks(params[:search_pattern], params[:word])
    else
      @books = Book.looks(params[:search_pattern], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_book_search.html.erb
<h2>Books Search for "<%= @word %>"</h2>
<table class='table table-hover table-inverse'>
 <thead>
   <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
   </tr>
 </thead>
 <tbody>
   <% @books.each do |book| %>
   <tr>
     <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
   </tr>
   <% end %>
 </tbody>
</table>

app/views/searches/_user_search.html.erb
<h2>Users Search for "<%= @word %>"</h2>
<table class='table table-hover table-inverse'>
 <thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th></th>
     <th colspan="3"></th>
   </tr>
 </thead>
 <tbody>
   <% @users.each do |user| %>
   <tr>
     <td><%= image_tag user.get_profile_image, size:'50x50' %></td>
     <td><%= link_to user.name, user_path(user.id) %></td>
   </tr>
   <% end %>
 </tbody>
</table>

app/views/searches/search.html.erb
<% if @search_model == "user" %>
 <%= render 'user_search' %>
<% else %>
 <%= render 'book_search' %>
<% end %>